import { useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getCurrentEnv } from '../utils/tools'

export default function Home(props: any) {

  useEffect(() => {
    console.log('首页加载了===', getCurrentEnv())
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.skl}>this is skl config project</h3>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href="/skl-page/sklPage">点击跳转预渲染</Link>
        <div style={{ margin: '15px 0' }}>
          <Link href="/fetch/fetch">点击跳转获取数据页面</Link>
        </div>
        <div>
          <Link href="/list/[...skl]" as="/list/1/2">点击跳转动态路由页面</Link>
        </div>
        <div style={{ marginTop: '15px' }}>
          <Link href="/server-render/serverRender">服务端渲染</Link>
        </div>
      </main>
    </div>
  )
}
